require('plugin-config.which-key')
require('plugin-config.nvim-treesitter')
require('plugin-config.telescope')
require('plugin-config.nvim-autopairs')
-- require('plugin-config.nvim-tree')
require('plugin-config.bufferline')
require('plugin-config.folding')
require('plugin-config.surround')
require('plugin-config.comment')
require('plugin-config.nvim-colorizer')
require('plugin-config.windline')
require('plugin-config.markdown-preview')
